source 'https://ruby.taobao.org'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.4'
# Use postgresql as the database for Active Record
gem 'pg'
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use bower as js/css library management
gem "bower-rails", "~> 0.9.2"
# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc
# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

gem 'slim-rails'
gem 'omniauth'
gem 'aasm'
gem 'whenever', require: false
gem 'cancancan'
gem 'redis'
gem 'browser'
gem 'jquery-turbolinks'
gem 'momentjs-rails'
gem 'react-rails', :git => 'https://github.com/towry/react-rails.git'
gem 'webpackrails', '~> 2.0'
gem 'carrierwave', github: 'carrierwaveuploader/carrierwave'
gem 'mini_magick', require: false
gem 'sidekiq'
gem 'sinatra', require: false
gem 'valid_email'
gem 'meta-tags'
gem 'friendly_id'
gem 'rails-i18n', github: 'svenfuchs/rails-i18n', branch: 'master' # For 4.x
gem 'settingslogic'
gem "paranoia", "~> 2.0"
gem "animate-rails"

#peek
gem 'responders', '~> 2.0'
gem 'peek'
gem 'peek-pg'
gem 'peek-gc'
gem 'peek-sidekiq'
gem 'peek-redis'



# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
gem 'compass-rails', '~> 2.0.4'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'

gem 'jwt', '>= 1.5'
gem 'rack-mini-profiler', ">= 0.9.7"
gem 'stackprof'
gem 'flamegraph', ">= 0.1.0"
gem 'exception_notification'


group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring', '~> 1.3.5'
  gem 'bullet'
  gem 'awesome_print', require: false
end

group :development do
  gem 'guard-livereload', require: false
  gem 'guard-bundler', require: false
  gem 'guard-rails'
  gem 'guard-rspec'
  gem 'binding_of_caller'
  gem 'better_errors'
  gem 'did_you_mean'
  gem 'pry-rails'
  gem 'meta_request'
  gem 'xray-rails'
  gem 'letter_opener_web', '~> 1.2.0'
end

group :test do
  gem 'rspec-rails'
  gem 'spring-commands-rspec'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'shoulda-matchers', require: false
  gem 'database_cleaner'
  gem 'timecop'
end
